### PR TITLE
fix(options): nuxt options used in directive + merge overrides

### PR DESCRIPTION
**Pull request by lsimone**
First of all thanks for your package: it's easy to use and clear.

This PR is a fix I made when I realized nuxt options in `nuxt.config.ts` are not really taken into account when using the directive.

This is due to the fact that they where not included in [the sanitize-html method call](https://github.com/chantouchsek/v-sanitize/compare/master...Kampaay:master#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R38).

Furthermore, the option merge strategy were not doing what expected IMHO since if in the `nuxt.config.ts` I declare for instance:

```
sanitize: {
    allowedTags: ['a'],
    allowedAttributes: {
      a: ['href'],
    },
  }
```

merge result will just replace the first element of default `allowedTags` with `a` while it would be more useful to totally replace `allowedTags` entry with the user-defined one.

Hope this is welcome.
Lorenzo

### CODE REVIEW

**Comment by chantouchsek** [comment]
@lsimone can u resolve conflict?

**Comment by lsimone** [comment]
> @lsimone can u resolve conflict?

yep, done ;-)

**Review by chantouchsek — APPROVED** [review]
LGTM

**Comment by chantouchsek** [comment]
@lsimone release in [v0.0.6](https://github.com/chantouchsek/v-sanitize/releases/tag/v0.0.5)

**Pull request merged**
